# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-05 23:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_hash', models.CharField(editable=False, max_length=32)),
                ('biography', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('organization', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('location', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('user', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
