# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-06 00:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='StreamItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_object_id', models.PositiveIntegerField(blank=True, default=None, null=True)),
                ('theme_object_id', models.PositiveIntegerField(blank=True, default=None, null=True)),
                ('public', models.BooleanField(default=True)),
                ('verb', models.CharField(choices=[('join', 'joined'), ('view', 'viewed'), ('upvote', 'up voted'), ('downvote', 'down voted'), ('ask', 'asked'), ('answer', 'answered')], max_length=20)),
                ('details', models.TextField(blank=True, default=None, null=True)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_stream', to=settings.AUTH_USER_MODEL)),
                ('target_content_type', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='targets', to='contenttypes.ContentType')),
                ('theme_content_type', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='themes', to='contenttypes.ContentType')),
            ],
            options={
                'verbose_name_plural': 'activity stream items',
                'verbose_name': 'activity stream item',
                'ordering': ('-timestamp',),
                'db_table': 'activity_stream',
            },
        ),
    ]
